[package]
name = "psychotechnic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
pause_console = "0.1.3"
termion = "1.5.5"
